- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  
  - name: Delete and eradicate protection group snapshot
    purestorage.flasharray.purefa_pgsnap:
      name: eg-test-repl-pg
      suffix: ansible
      state: absent
      eradicate: yes
      fa_url: 10.225.112.90
      api_token: b5cb29e7-a93c-b40a-b02f-da2b90c8c65e
