- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Create a virtual machine on given ESXi hostname
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      state: poweredoff
      guest_id: "{{ vm_guest_id }}"
      disk:
      - size_gb: "{{ vm_disk_size_gb }}"
        type: thin
        datastore:  "{{ datastore_name }}"
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_num_cpus }}"
        scsi: paravirtual
      networks:
      - name: "{{ vm_network }}"
        device_type: "{{ vm_network_type }}"
      validate_certs: false
    delegate_to: localhost
