- name: Create dnsmasq configuration directory
  ansible.builtin.file:
    path: "{{ dnsmasq_conf_file | dirname }}"
    state: directory
    mode: '0755'

- name: Create dnsmasq configuration
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ dnsmasq_conf_file }}"
